// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/user": {
    params: {};
  };
  "/user/bookings": {
    params: {};
  };
  "/user/mentors": {
    params: {};
  };
  "/user/ai-chat": {
    params: {};
  };
  "/user/payments": {
    params: {};
  };
  "/user/profile": {
    params: {};
  };
  "/mentor": {
    params: {};
  };
  "/mentor/schedule": {
    params: {};
  };
  "/mentor/skills": {
    params: {};
  };
  "/mentor/bookings": {
    params: {};
  };
  "/mentor/ai-chat": {
    params: {};
  };
  "/mentor/profile": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/mentors": {
    params: {};
  };
  "/admin/bookings": {
    params: {};
  };
  "/admin/payments": {
    params: {};
  };
  "/admin/health": {
    params: {};
  };
  "/unauthorized": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page:
      | "/"
      | "/about"
      | "/login"
      | "/register"
      | "/user"
      | "/user/bookings"
      | "/user/mentors"
      | "/user/ai-chat"
      | "/user/payments"
      | "/user/profile"
      | "/mentor"
      | "/mentor/schedule"
      | "/mentor/skills"
      | "/mentor/bookings"
      | "/mentor/ai-chat"
      | "/mentor/profile"
      | "/admin"
      | "/admin/mentors"
      | "/admin/bookings"
      | "/admin/payments"
      | "/admin/health"
      | "/unauthorized";
  };
  "routes/public/_layout.tsx": {
    id: "routes/public/_layout";
    page: "/" | "/about";
  };
  "routes/public/home.tsx": {
    id: "routes/public/home";
    page: "/";
  };
  "routes/public/about.tsx": {
    id: "routes/public/about";
    page: "/about";
  };
  "routes/auth/_layout.tsx": {
    id: "routes/auth/_layout";
    page: "/login" | "/register";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "routes/user/_layout.tsx": {
    id: "routes/user/_layout";
    page:
      | "/user"
      | "/user/bookings"
      | "/user/mentors"
      | "/user/ai-chat"
      | "/user/payments"
      | "/user/profile";
  };
  "routes/user/dashboard.tsx": {
    id: "routes/user/dashboard";
    page: "/user";
  };
  "routes/user/bookings.tsx": {
    id: "routes/user/bookings";
    page: "/user/bookings";
  };
  "routes/user/find-mentors.tsx": {
    id: "routes/user/find-mentors";
    page: "/user/mentors";
  };
  "routes/user/ai-chat.tsx": {
    id: "routes/user/ai-chat";
    page: "/user/ai-chat";
  };
  "routes/user/payments.tsx": {
    id: "routes/user/payments";
    page: "/user/payments";
  };
  "routes/user/profile.tsx": {
    id: "routes/user/profile";
    page: "/user/profile";
  };
  "routes/mentor/_layout.tsx": {
    id: "routes/mentor/_layout";
    page:
      | "/mentor"
      | "/mentor/schedule"
      | "/mentor/skills"
      | "/mentor/bookings"
      | "/mentor/ai-chat"
      | "/mentor/profile";
  };
  "routes/mentor/dashboard.tsx": {
    id: "routes/mentor/dashboard";
    page: "/mentor";
  };
  "routes/mentor/schedule.tsx": {
    id: "routes/mentor/schedule";
    page: "/mentor/schedule";
  };
  "routes/mentor/skills.tsx": {
    id: "routes/mentor/skills";
    page: "/mentor/skills";
  };
  "routes/mentor/bookings.tsx": {
    id: "routes/mentor/bookings";
    page: "/mentor/bookings";
  };
  "routes/mentor/ai-chat.tsx": {
    id: "routes/mentor/ai-chat";
    page: "/mentor/ai-chat";
  };
  "routes/mentor/profile.tsx": {
    id: "routes/mentor/profile";
    page: "/mentor/profile";
  };
  "routes/admin/_layout.tsx": {
    id: "routes/admin/_layout";
    page:
      | "/admin"
      | "/admin/mentors"
      | "/admin/bookings"
      | "/admin/payments"
      | "/admin/health";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin";
  };
  "routes/admin/mentors.tsx": {
    id: "routes/admin/mentors";
    page: "/admin/mentors";
  };
  "routes/admin/bookings.tsx": {
    id: "routes/admin/bookings";
    page: "/admin/bookings";
  };
  "routes/admin/payments.tsx": {
    id: "routes/admin/payments";
    page: "/admin/payments";
  };
  "routes/admin/health.tsx": {
    id: "routes/admin/health";
    page: "/admin/health";
  };
  "routes/errors/unauthorized.tsx": {
    id: "routes/errors/unauthorized";
    page: "/unauthorized";
  };
};

type RouteModules = {
  root: typeof import("./app/root.tsx");
  "routes/public/_layout": typeof import("./app/routes/public/_layout.tsx");
  "routes/public/home": typeof import("./app/routes/public/home.tsx");
  "routes/public/about": typeof import("./app/routes/public/about.tsx");
  "routes/auth/_layout": typeof import("./app/routes/auth/_layout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
  "routes/user/_layout": typeof import("./app/routes/user/_layout.tsx");
  "routes/user/dashboard": typeof import("./app/routes/user/dashboard.tsx");
  "routes/user/bookings": typeof import("./app/routes/user/bookings.tsx");
  "routes/user/find-mentors": typeof import("./app/routes/user/find-mentors.tsx");
  "routes/user/ai-chat": typeof import("./app/routes/user/ai-chat.tsx");
  "routes/user/payments": typeof import("./app/routes/user/payments.tsx");
  "routes/user/profile": typeof import("./app/routes/user/profile.tsx");
  "routes/mentor/_layout": typeof import("./app/routes/mentor/_layout.tsx");
  "routes/mentor/dashboard": typeof import("./app/routes/mentor/dashboard.tsx");
  "routes/mentor/schedule": typeof import("./app/routes/mentor/schedule.tsx");
  "routes/mentor/skills": typeof import("./app/routes/mentor/skills.tsx");
  "routes/mentor/bookings": typeof import("./app/routes/mentor/bookings.tsx");
  "routes/mentor/ai-chat": typeof import("./app/routes/mentor/ai-chat.tsx");
  "routes/mentor/profile": typeof import("./app/routes/mentor/profile.tsx");
  "routes/admin/_layout": typeof import("./app/routes/admin/_layout.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/mentors": typeof import("./app/routes/admin/mentors.tsx");
  "routes/admin/bookings": typeof import("./app/routes/admin/bookings.tsx");
  "routes/admin/payments": typeof import("./app/routes/admin/payments.tsx");
  "routes/admin/health": typeof import("./app/routes/admin/health.tsx");
  "routes/errors/unauthorized": typeof import("./app/routes/errors/unauthorized.tsx");
};
