// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/login" | "/register";
  };
  "routes/public/_layout.tsx": {
    id: "routes/public/_layout";
    page: "/" | "/about";
  };
  "routes/public/home.tsx": {
    id: "routes/public/home";
    page: "/";
  };
  "routes/public/about.tsx": {
    id: "routes/public/about";
    page: "/about";
  };
  "routes/auth/_layout.tsx": {
    id: "routes/auth/_layout";
    page: "/login" | "/register";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
};

type RouteModules = {
  root: typeof import("./app/root.tsx");
  "routes/public/_layout": typeof import("./app/routes/public/_layout.tsx");
  "routes/public/home": typeof import("./app/routes/public/home.tsx");
  "routes/public/about": typeof import("./app/routes/public/about.tsx");
  "routes/auth/_layout": typeof import("./app/routes/auth/_layout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
};
